@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic #C8C8FA
participant ":EditPackageCommand" as EditPackageCommand #3333C4
end box

box Model #F97181
participant ":Model" as Model #9D0012
participant ":InsuranceCatalog" as InsuranceCatalog #9D0012
participant ":UniqueInsurancePackageList" as UniqueInsurancePackageList #9D0012
end box

[-> EditPackageCommand : execute(model)
activate EditPackageCommand

EditPackageCommand -> Model : getCatalog()
activate Model
Model --> EditPackageCommand : catalog
deactivate Model

EditPackageCommand -> InsuranceCatalog : getPackageList()
activate InsuranceCatalog
InsuranceCatalog --> EditPackageCommand : packageList
deactivate InsuranceCatalog

EditPackageCommand -> UniqueInsurancePackageList : findPackageByName(name)
activate UniqueInsurancePackageList

UniqueInsurancePackageList --> EditPackageCommand : targetP
deactivate UniqueInsurancePackageList

alt targetP == null
    <-- EditPackageCommand : CommandException
else targetP != null
    EditPackageCommand -> "editedP:InsurancePackage" ** #00008B : create(name, newDescription)
    activate "editedP:InsurancePackage"
    "editedP:InsurancePackage" --> EditPackageCommand : editedP
    deactivate "editedP:InsurancePackage"

    EditPackageCommand -> Model : setInsurancePackage(targetP, editedP)
        activate Model

        Model -> InsuranceCatalog : setInsurancePackage(targetP, editedP)
        activate InsuranceCatalog

        InsuranceCatalog -> UniqueInsurancePackageList : setInsurancePackage(targetP, editedP)
        activate UniqueInsurancePackageList

        UniqueInsurancePackageList --> InsuranceCatalog
        deactivate UniqueInsurancePackageList

        InsuranceCatalog --> Model
        deactivate InsuranceCatalog

        Model --> EditPackageCommand
        deactivate Model

    <-- EditPackageCommand : CommandResult
    deactivate EditPackageCommand
end
@enduml
