@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic #C8C8FA
participant ":EditPackageCommand" as EditCmd #3333C4
end box

box Model #F97181
participant ":Model" as M #9D0012
participant ":InsuranceCatalog" as Catalog #9D0012
participant ":UniqueInsurancePackageList" as PkgList #9D0012
end box

[-> EditCmd : execute(model)
activate EditCmd

EditCmd -> M : getInsuranceCatalog()
activate M
M --> EditCmd : catalog
deactivate M

ref over EditCmd, Catalog, PkgList : Find targetPackage by name (stream & filter)


alt targetPackage == null
    <-- EditCmd : CommandException(MESSAGE_INVALID_PACKAGE)
else targetPackage != null
    EditCmd -> InsurancePackage ** #00008B : create(name, newDesc)
    activate InsurancePackage
    InsurancePackage --> EditCmd : editedPackage
    deactivate InsurancePackage

    EditCmd -> M : setInsurancePackage(oldPackage, editedPackage)
        activate M

        M -> Catalog : setInsurancePackage(oldPackage, editedPackage)
        activate Catalog

        Catalog -> PkgList : setInsurancePackage(oldPackage, editedPackage)
        activate PkgList

        PkgList --> Catalog
        deactivate PkgList

        Catalog --> M
        deactivate Catalog

        M --> EditCmd
        deactivate M

    <-- EditCmd : CommandResult (success, editedPackage)
    deactivate EditCmd
end
@enduml