@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":ExportCommandParser" as ExportCommandParser LOGIC_COLOR
participant "e:ExportCommand" as ExportCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant "ab:AddressBook" as AddressBook MODEL_COLOR
end box

[-> LogicManager : execute("export")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("export")
activate AddressBookParser

create ExportCommandParser
AddressBookParser -> ExportCommandParser : parse(arguments)
activate ExportCommandParser

create ExportCommand
ExportCommandParser -> ExportCommand
activate ExportCommand

ExportCommand --> ExportCommandParser
deactivate ExportCommand

ExportCommandParser --> AddressBookParser
deactivate ExportCommandParser

AddressBookParser --> LogicManager
deactivate AddressBookParser

LogicManager -> ExportCommand : execute()
activate ExportCommand

ExportCommand -> Model : getAddressBook()
activate Model

Model --> ExportCommand
deactivate Model

ExportCommand -> AddressBook : getPersonList()
activate AddressBook

AddressBook --> ExportCommand : personList
deactivate AddressBook

create CommandResult
ExportCommand -> CommandResult
activate CommandResult

CommandResult --> ExportCommand
deactivate CommandResult

ExportCommand --> LogicManager
deactivate ExportCommand

[<--LogicManager
deactivate LogicManager
@enduml